[package]
name = "newdoc"
version = "2.9.5"
description = "Generate pre-populated module files formatted with AsciiDoc that are used in Red Hat and Fedora documentation."
authors = ["Marek Suchánek <msuchane@redhat.com>"]
license = "GPL-3.0-or-later"
edition = "2021"
documentation = "https://docs.rs/newdoc"
readme = "README.md"
repository = "https://github.com/mrksu/newdoc"
categories = ["command-line-utilities", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^3", features = ["cargo"] }
regex = "1"
log = "0.4"
simplelog = "0.11"
askama = "0.11"


[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
newdoc = { path = "/usr/bin/newdoc" }
