[package]
name = "newdoc"
version = "2.2.0"
description = "The newdoc tool generates pre-populated module and assembly files formatted with AsciiDoc, which are used in Red Hat and Fedora documentation. The generated files follow the template guidelines maintained by the Modular Documentation initiative: https://redhat-documentation.github.io/modular-docs/."
authors = ["Marek Suchánek <marek.suchanek@protonmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"
documentation = "https://docs.rs/newdoc"
readme = "README.md"
repository = "https://github.com/mrksu/newdoc"
categories = ["command-line-utilities", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"


[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
newdoc = { path = "/usr/bin/newdoc" }
