name: RPM build

on:
  push:
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/ubi

    steps:
    - name: Set up build tools
      run: |
        yum install microdnf -y
        microdnf install rpm-build
        microdnf module enable rust-toolset
        microdnf install rust-toolset
    - name: Install cargo-rpm
      run: cargo install cargo-rpm
    - uses: actions/checkout@v3
    - name: Build the RPM package
      run: cargo rpm build --verbose
    - name: Store the newdoc binary as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: newdoc-binary
        path: target/release/newdoc
    - name: Store the built RPMs as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: newdoc-rpmbuild
        path: target/release/rpmbuild
