name: Rust

on:
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/ubi

    steps:
    - uses: actions/checkout@v2
    - name: Set up build tools
      run: yum module install rust-toolset
    - name: Check syntax
      run: cargo check --verbose
