name: Rust Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/ubi

    steps:
    - uses: actions/checkout@v3
    - name: Set up build tools
      run: yum module install rpm-build rust-toolset -y
    - name: Install cargo-rpm
      run: cargo install cargo-rpm
    - name: Build the RPM package
      run: cargo rpm build --verbose
    - name: Store the built RPM as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: rpm-artifact
        path: target/release
