name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check syntax
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check lints
      run: cargo clippy --verbose
